---
# gets tags based off this handy and excellent answer https://stackoverflow.com/a/67404585/17214978
- name: get latest stable version tag
  ansible.builtin.shell:
    cmd: curl --silent 'https://api.github.com/repos/daniruiz/flat-remix-gtk/tags' | jq -r '.[0].name'
  register: flat_remix_release
  changed_when: false
  args:
    warn: false

- name: clone flat remix gtk
  ansible.builtin.script: "{{ flat_remix_gtk_version }}"
  changed_when: false

- name: sync updated flat remix gtk elements
  ansible.posix.synchronize:
    src: "/tmp/flat-remix-gtk/themes/"
    dest: ~/.local/share/themes/
    rsync_opts:
      - "-u"
      - "-a"
      - "--include=Flat-Remix-GTK-*"
      - "--include=Flat-Remix-GTK-*/**"
      - "--exclude=*"
