---
- name: check if flat remix icons is already installed
  stat:
    path: ~/.local/share/icons/Flat-Remix-Black-Dark
  register: flat_remix

- name: clone flat remix icons
  ansible.builtin.git:
    repo: https://github.com/daniruiz/flat-remix
    dest: /tmp/flat-remix
    clone: yes
    depth: 1
    version: "{{ flat_remix_icon_version }}"
    track_submodules: no
    recursive: no
  when: not flat_remix.stat.exists

- name: sync updated flat remix icons
  ansible.posix.synchronize:
    src: "/tmp/flat-remix-gtk/"
    dest: ~/.local/share/themes/
    rsync_opts:
      - "-u"
      - "-a"
      - "--delete"
      - "--include=Flat-Remix-*"
      - "--include=Flat-Remix-*/**"
      - "--exclude=*"
  delegate_to: "{{ inventory_hostname }}"
  when: not flat_remix.stat.exists

- name: cleanup
  file:
    state: absent
    path: /tmp/flat-remix
  when: not flat_remix.stat.exists
