########################################################################################################################
# dot files
########################################################################################################################

use_dotfiles: false
dotfile_path: ""
dotfile_url: ""
clone_commands:
  - git clone '{{ dotfile_url }}'

########################################################################################################################
# shell shell
########################################################################################################################
set_shell: false
chosen_shell: ""
update_config_command: source ""

########################################################################################################################
# install packages apt
########################################################################################################################
use_apt_cache: false
cache_url: ""

install_apt_packages: false
packages_remove:
  - ""

packages_install:
  - ""

########################################################################################################################
# install packages flatpak
########################################################################################################################
install_flatpaks: false
flatpaks_install:
  - ""

########################################################################################################################
# install packages snap
########################################################################################################################

install_snaps: false
strict_snaps:
  - ""

classic_snaps:
  - ""

########################################################################################################################
# install extensions vscode
########################################################################################################################

install_vscode_extensions: false
code_insiders: false
code_base: false
vs_code_extensions:
  - ""

########################################################################################################################
# install extensions gnome
########################################################################################################################

install_gnome_extensions: false
gnome_apt_ext:
  - ""

########################################################################################################################
# gnome settings
########################################################################################################################

set_profile: false
user_profile_img: ""

set_clock: false

set_privacy: false

configure_power: false

disable_dash_keybindings: false

set_keybindings: false
keybindings:
  "/org/gnome/settings-daemon/plugins/media-keys/terminal": "['<Super>t']" # example
custom-keys-script: ""
disable-keys-script: ""

set_settings_tweaks: false
settings_tweaks:
  "/org/gnome/desktop/interface/enable-hot-corners": "false" # example


########################################################################################################################
# theming
########################################################################################################################

set_wallpaper: false
user_wall_img: ""
wallpaper_location: ""

set_theme: false
gtk_theme_name: ""
cursor_theme_name: ""
icon_theme_name: ""

install_theme_packages: false
theme_apt_pkg:
  - ""