---
- hosts: all
  # https://stackoverflow.com/questions/21870083/specify-sudo-password-for-ansible
  vars_files:
    - secret
  roles:
    - role: core_software
    - role: directories
    - role: docker
    - role: fonts
    - role: oxygen_icons
    - role: vscode
    - role: systemd
    - role: tlp
    - role: flat_remix
    - role: gnome
    - role: extensions
