---
- name: install core utilities
  become: yes
  ansible.builtin.apt:
    name:
      "{{ core_packages }}"
    state: present

- name: purge uneeded
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ remove_packages }}"
