---
- name: install flatpak
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present

- name: setup flathub repo
  ansible.builtin.command: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  # become: true
  changed_when: false

- name: install the packages from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items: "{{ flatpaks }}"
