---
- name: install pip
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ pip_pkgs }}"
