---
- name: install pip
  become: yes
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: install pip packages
  pip:
    name:
      - ansible
      - ansible-lint
      - yamllint
