---
- name: install python tools & libraries from the repo
  become: yes
  ansible.builtin.package:
    name:
      - pycodestyle
      - pylint
      - python-is-python3
      - python3-autopep8
      - python3-dev
      - python3-pyqt5
      - python3-rope
    state: present
