---
- name: install snapd
  become: yes
  ansible.builtin.package:
    name: snapd
    state: present

- name: install strict snaps
  become: yes
  community.general.snap:
    name: "{{ item }}"
  with_items: "{{ snaps_strict }}"
  changed_when: false

- name: install classic snaps
  become: yes
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  with_items: "{{ snaps_classic }}"
  changed_when: false
