---
- name: install vscode & vscode-insiders
  become: yes
  community.general.snap:
    name:
      - code
      - code-insiders
    classic: yes

- name: install vscode-insiders extensions
  ansible.builtin.command: code-insiders --install-extension "{{ item }}"
  with_items: "{{ vs_code_extensions }}"
  changed_when: false

- name: install vscode extensions
  ansible.builtin.command: code --install-extension "{{ item }}"
  with_items: "{{ vs_code_extensions }}"
  changed_when: false
