---
- name: remove dashtodock bindings
  ansible.builtin.script: "{{ disable_keys_script }}"
  
- name: set keybindings
  ansible.builtin.dconf:
    key: "{{ item.key}}"
    value: "{{ item.value}}"
  with_dict:
  - "{{ keybindings }}"

- name: create custom keybinds with script
  ansible.builtin.script: "{{ custom_keys_script }}"