---
- name: copy systemd files
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0640'
  with_fileglob:
    - files/*

- name: enable and start the services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items: "{{ systemd_enable }}"
  changed_when: false
