---
- name: copy systemd files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0640"
  with_fileglob:
    - files/*

- name: enable and start the services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: started
  with_items: "{{ systemd_enable }}"
  changed_when: false
