---
- name: check if flatpak is installed
  ansible.builtin.command: which flatpak
  register: is_installed
  changed_when: false

- name: update flatpaks
  become: true
  ansible.builtin.command: flatpak update --noninteractive
  changed_when: false
  when: is_installed.rc == 0
