---
- name: configure privacy settings
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ privacy_settings }}"

# https://askubuntu.com/questions/1029108/how-do-i-programmatically-disable-connectivity-checking
- name: remove connectivity checking
  become: false
  ansible.builtin.shell: |
    busctl --system set-property org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.NetworkManager ConnectivityCheckEnabled "b" 0
  changed_when: false
