- name: workspaces span displays
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "true"
- name: app-switcher on the current workspace only
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
- name: detach modal dialogs
  dconf:
    key: "/org/gnome/shell/overrides/attach-modal-dialogs"
    value: "false"
- name: enable two-finger scrolling
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"
- name: disable hot corner  
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"