---
- hosts: all

  pre_tasks:
    - name: load configuration
      ansible.builtin.include_vars: config.yml

  tasks:
    - name: download dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      when: use_dotfiles

    - name: set default shell to fish
      ansible.builtin.import_tasks: tasks/fish.yml
      when: set_fish

