---
- name: check if dotfile repo has already been cloned
  stat: path="{{ dotfile_path }}"
  register: repo_exists

- name: clone dotfiles
  ansible.builtin.command: "{{ item }}"
  with_items: "{{ clone_commands }}" 
  when: not repo_exists.stat.exists